services:
  crm_rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
  crm_redis:
    image: redis:7
    ports:
      - "6379:6379"
  api_gateway:
    build:
      context: ./apps/api-gateway/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - events_microservice
      - users_microservice
      - leads_microservice
      - clients_microservice
      - deals_microservice
      - notes_microservice
      - tasks_microservice
  events_microservice:
    build:
      context: ./apps/events-microservice/
      dockerfile: ./Dockerfile
    depends_on:
      - events_database
      - crm_rabbitmq
  users_microservice:
    build:
      context: ./apps/users-microservice/
      dockerfile: ./Dockerfile
    depends_on:
      - users_database
      - crm_rabbitmq
  leads_microservice:
    build:
      context: ./apps/leads-microservice/
      dockerfile: ./Dockerfile
    depends_on:
      - leads_database
      - crm_rabbitmq
  clients_microservice:
    build:
      context: ./apps/clients-microservice/
      dockerfile: ./Dockerfile
    depends_on:
      - clients_database
      - crm_rabbitmq
  deals_microservice:
    build:
      context: ./apps/deals-microservice/
      dockerfile: ./Dockerfile
    depends_on:
      - deals_database
      - crm_rabbitmq
  notes_microservice:
    build:
      context: ./apps/notes-microservice/
      dockerfile: ./Dockerfile
    depends_on:
      - notes_database
      - crm_rabbitmq
  tasks_microservice:
    build:
      context: ./apps/tasks-microservice/
      dockerfile: ./Dockerfile
    depends_on:
      - tasks_database
      - crm_rabbitmq
  users_database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "crm_users_database"
    ports:
      - "5432:5432"
  leads_database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "crm_leads_database"
    ports:
      - "5433:5432"
  clients_database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "crm_clients_database"
    ports:
      - "5434:5432"
  events_database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "crm_events_database"
    ports:
      - "5435:5432"
  deals_database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "crm_deals_database"
    ports:
      - "5436:5432"
  tasks_database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "crm_tasks_database"
    ports:
      - "5437:5432"
  notes_database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "crm_notes_database"
    ports:
      - "5438:5432"
  auth_sessions_database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "crm_auth_sessions_database"
    ports:
      - "5439:5432"
